version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wesave_back
    container_name: wesave_back_app
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
